### PR TITLE
Fix for using lingual with tcsv directories on Hadoop cluster with part files in the directory

### PR DESCRIPTION
**Pull request by choss**
In regards to the discussion in the lingual user group here: https://groups.google.com/forum/#!topic/lingual-user/7-GzLgTO7PU

The summary of the topic is: 
Suppose we have and example structure (created via cascading job) like below on the hadoop cluster:

 /logfiles/D2014_02_18/service1.tcsv/part-00000-00001
 /logfiles/D2014_02_18/service1.tcsv/part-00001-00000
 /logfiles/D2014_02_18/service1.tcsv/part-00002-00021
 /logfiles/D2014_02_18/service1.tcsv/part-00004-00005

 /logfiles/D2014_02_18/service2.tcsv/part-00000-00001
 /logfiles/D2014_02_18/service2.tcsv/part-00001-00000
 /logfiles/D2014_02_18/service2.tcsv/part-00002-00021
 /logfiles/D2014_02_18/service2.tcsv/part-00004-00005

We then invoke the lingual shell like this: pc:~/test$ lingual shell --config schemas=/logfiles/D2014_02_18 --platform hadoop --resultPath=/results --verbose

Lingual correctly enumerates all tables and creates the tables service1 and service2 in the D2014_02_18 schema. Unfortunately it does not read the TCSV information from the part file and therefore does not allow any operation on those files. 

I have created a fix for this which only works (and is only supposed to work) on the hadoop platform. 
The test case had to be changed a bit, since the result comparison relied on the order of the data in the resultset. Unfortunately I do not know how to restrict the test only to work with the hadoop platform, therefore this is not implemented. The test is fully green otherwise

### CODE REVIEW

**Comment by joeposner** [comment]
While this fix is valid for the case described it has side effects that may cause Lingual to treat files differently than other Cascading libraries do. Therefor this change should be made in Cascading, not Lingual. For example, it could amend the FileType interface in Cascading to support exists() and/or isEmpty(). At that point, Lingual can use those methods rather than a size() == 0 check.

**Comment by choss** [comment]
Why would lingual treat files differently than other cascading applications? From my understanding, it is the expected behaviour in hadoop to read the whole directory if it contains "part" files. (The javadoc in the cascading Hfs class also states this). Cascading transparently also handles this case. 
The bugfix is in my opinion just in lingual, to also read the metadata automatically from this kind of directory structure. When using the shell lingual already can do it for the "resultPath" of an query, if the sql was done in the same session.

Nevertheless I agree, that some more convinience methods in cascading definitely can help to make the code better.

**Comment by joeposner** [comment]
I agree that with the current code this wouldn't currently cause any differences. My concern was to avoid a case where we fix the issue in Lingual now and then end up adding in the methods to FileType in Cascading later to fix a different issue.

**Comment by choss** [comment]
Okay I fully understand now. It definitely makes sense to push the fix to cascading. Could you take it up with the group maintaining cascading please?

**Comment by cwensel** [comment]
I’m looking at a fix for this in Lingual, thanks for the test.

but, yes, you should be able to use nested part files in directories as simply as them being single files.

ckw

**Comment by choss** [comment]
Thank you very much!

**Comment by cwensel** [comment]
give the latest Lingual 1.1 wip a run and see if it resolves your issues.

On Mar 3, 2014, at 5:29 AM, choss notifications@github.com wrote:

> Thank you very much!
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by choss** [comment]
Yes my issues are resolved. Thank you very much!

**Comment by concurrentinc** [comment]
great news!

On Mar 4, 2014, at 9:22 AM, choss notifications@github.com wrote:

> Closed #18.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Pull request closed without merging**
