### PR TITLE
Improved error reporting

### PR DESCRIPTION
**Pull request by jkot**
Improved error reporting, see Issue #7

### CODE REVIEW

**Comment by joeposner** [comment]
Thanks for the pull request and the feedback. I'm a huge fan of anything that makes the error reporting clearer.

But before we take the pull request can you make the following changes:
- Undo the change to the slf4j version. It's outdated on purpose because at runtime we rely on the environment context to provide slf4j jars. Since many of our supported environments aren't on 1.7.x and since 1.7.x adds support for varargs we need to stick with compiling against the 1.6.x version.
- Change your code formatting to match our style. I know we use an odd style, but...
- In the case you're handling you're 100% right that the parent message isn't the "real" one but that's not always true. Can you rename the method to something that makes it clear that sometimes the parent throwable is the source of the problem and sometimes the child throwable is the source of the problem? I know this is nitpicking but as you point out, little things like this can make a big difference.

**Comment by jkot** [comment]
No problem.

slf4j version change undone. Code formatting changed. 
I renamed the method to assembleCause() - this way it also won't be confused with a bean get method, if you prefer another name, let me know, I'll change it. 

Thanks for the fast reply

**Comment by joeposner** [comment]
Thanks. Can you send me your preferred email to jposner@concurrentinc.com so I can send you our standard 2-page contributor agreement?

**Comment by cwensel** [comment]
thanks! i've merge this with some minor cleanup.

**Pull request closed without merging**
