### PR TITLE
upgrade Asciidoctor Gradle Plugin to 0.7.0

### PR DESCRIPTION
**Pull request by mojavelinux**
- update include paths to be relative to project directory
- put space between include files

### CODE REVIEW

**Comment by cwensel** [comment]
Thanks!

Gave it a quick try and get 

```
asciidoctor: WARNING: file does not exist or cannot be read: /Users/..../lingual/src/site/stylesheets/cascading.css
asciidoctor: WARNING: image to embed not found or not readable: /Users/..../lingual/src/site/images/gina_hire_age.png
```

Seems current project dir is not being honored still

**Comment by mojavelinux** [comment]
Did you execute gradle from the root project? I ran it from the docs
subproject. That could explain our different results. If so, then I need to
figure out why.

**Comment by cwensel** [comment]
yes, ran it from the root. 

gradle will search all sub-projects and run the matching commands. 

for example

```
gradle jar
```

will jar all the subprojects relative to their sub-project path. the same would be expected with `asciidoctor` task

On Oct 11, 2013, at 4:21 PM, Dan Allen notifications@github.com wrote:

> Did you execute gradle from the root project? I ran it from the docs
> subproject. That could explain our different results. If so, then I need to
> figure out why.
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by mojavelinux** [comment]
Got it. I just wanted to confirm to be sure I was chasing the right rabbit :)

**Comment by mojavelinux** [comment]
I've updated the pull requests. The problem resolving the stylesheet path was a bug in the custom document template. The problem resolving the images path is a bug in Asciidcotor.

To explain further, when the safe mode is set to UNSAFE, the asset paths are not being resolved relative to the base directory. We can't raise the safe mode level in the Gradle plugin because it's hard coded. Once that's solved, I recommend switching to the safe mode SAFE since you don't want Asciidoctor resolving paths outside of the project anyway.

This pull request should be good to go now.

**Pull request closed without merging**
