### PR TITLE
Added unit test about outgoing values selector that cannot be resolved

### PR DESCRIPTION
**Pull request by rdelbru**
Hi Chris,

here is one query that seems to cause problem in the cascading planner. It looks like that the cause is related to variables using a different table alias, but the same column name.

```
Caused by: cascading.pipe.OperatorException: [{0}lhs*rhs][cascading.lingual.optiq.CalcProjectUtil.addRename(CalcProjectUtil.java:117)] could not resolve outgoing values selector in: Each({0}lhs*rhs)[Identity[decl:'CITY']]
    at cascading.pipe.Each.resolveOutgoingValuesSelector(Each.java:408)
    at cascading.pipe.Each.outgoingScopeFor(Each.java:384)
    at cascading.flow.planner.ElementGraph.resolveFields(ElementGraph.java:628)
    at cascading.flow.planner.ElementGraph.resolveFields(ElementGraph.java:610)
    at cascading.flow.local.planner.LocalPlanner.buildFlow(LocalPlanner.java:95)
    ... 52 more
Caused by: cascading.tuple.TupleException: field name already exists: CITY
    at cascading.tuple.Fields.copyRetain(Fields.java:1327)
    at cascading.tuple.Fields.append(Fields.java:1197)
    at cascading.pipe.Operator.resolveOutgoingSelector(Operator.java:312)
    at cascading.pipe.Each.resolveOutgoingValuesSelector(Each.java:401)
    ... 56 more
```

### CODE REVIEW

**Comment by concurrentinc** [comment]
am able to reproduce, waiting on a code drop, then will take a shot at it if the new code doesn't resolve the issue.

On May 15, 2013, at 3:18 PM, Renaud Delbru notifications@github.com wrote:

> Hi Chris,
> 
> here is one query that seems to cause problem in the cascading planner. It looks like that the cause is related to variables using a different table alias, but the same column name.
> 
> Caused by: cascading.pipe.OperatorException: [{0}lhs_rhs][cascading.lingual.optiq.CalcProjectUtil.addRename(CalcProjectUtil.java:117)] could not resolve outgoing values selector in: Each({0}lhs_rhs)[Identity[decl:'CITY']]
>     at cascading.pipe.Each.resolveOutgoingValuesSelector(Each.java:408)
>     at cascading.pipe.Each.outgoingScopeFor(Each.java:384)
>     at cascading.flow.planner.ElementGraph.resolveFields(ElementGraph.java:628)
>     at cascading.flow.planner.ElementGraph.resolveFields(ElementGraph.java:610)
>     at cascading.flow.local.planner.LocalPlanner.buildFlow(LocalPlanner.java:95)
>     ... 52 more
> Caused by: cascading.tuple.TupleException: field name already exists: CITY
>     at cascading.tuple.Fields.copyRetain(Fields.java:1327)
>     at cascading.tuple.Fields.append(Fields.java:1197)
>     at cascading.pipe.Operator.resolveOutgoingSelector(Operator.java:312)
>     at cascading.pipe.Each.resolveOutgoingValuesSelector(Each.java:401)
>     ... 56 more
> You can merge this Pull Request by running
> 
>   git pull https://github.com/rdelbru/lingual upstream
> Or view, comment on, or merge it at:
> 
>   https://github.com/Cascading/lingual/pull/1
> 
> Commit Summary
> 
> Added unit test about outgoing values selector that cannot be resolved
> File Changes
> 
> M lingual-platform/src/test/java/cascading/lingual/jdbc/SimpleSqlPlatformTest.java (14)
> Patch Links:
> 
> https://github.com/Cascading/lingual/pull/1.patch
> https://github.com/Cascading/lingual/pull/1.diff

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by cwensel** [comment]
we are still working on this issue, hopefully will be resolved later this week

**Comment by rdelbru** [comment]
Thanks for the update.

**Comment by cwensel** [comment]
OK, we ran this query against MySQL and the test results you expect are not what it returns.

I'll add this test with what we believe are the actual expected results and push it out today.

**Comment by rdelbru** [comment]
Great, thanks Chris. I'll try the patch on my environment and let you know.

**Comment by rdelbru** [comment]
Hi Chris,

In me environment, some of my tests are now successful, but some of them are still encountering the same problem. I will try to make a pull request with a query showing the problem.

**Comment by rdelbru** [comment]
In fact, the problem was coming on my code. I do not encounter anymore this problem.

**Pull request closed without merging**
